#!/usr/bin/env bash
cd "$(dirname "$0")"

if [ -e default.nix ]; then
    rm default.nix*
fi

if [ -e .Rprofile ]; then
    rm .Rprofile
fi

if [ -e result ]; then
    rm result
fi

Rscript setup.R
nix-build

read -p "Press Enter to close..."
exit
